#pragma once
#include "app.h"
#include "Core.h"
#include "timing.h"
#include "Precision.h"
#include "Particle.h"
#include <GL/freeglut.h>
#include <GL/freeglut_ext.h>
#include <GL/freeglut_std.h>
#include <GL/glut.h>
#include <cstring>
#include <cstdio>